import type { AgentResult, Agent, OfficeAgent } from '../types';
import { sanitizeFilename, redactSecrets } from './sanitize';

function triggerDownload(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function agentFileName(agentName: string): string {
  return sanitizeFilename(agentName.replace(/\s+/g, '-').toLowerCase());
}

export function exportResultAsMarkdown(result: AgentResult, _agent: Agent | undefined): void {
  const md = [
    `# ${result.agent_name}`,
    '',
    `Status: ${result.status}`,
    `Tokens: ${result.tokens_used}`,
    `Cost: $${result.cost_usd.toFixed(4)}`,
    `Time: ${result.elapsed_ms ? (result.elapsed_ms / 1000).toFixed(1) + 's' : 'N/A'}`,
    '',
    '---',
    '',
    redactSecrets(result.response),
    '',
  ].join('\n');
  triggerDownload(md, `${agentFileName(result.agent_name)}-result.md`, 'text/markdown');
}

export function exportResultsAsMarkdown(results: AgentResult[], agents: Agent[]): void {
  const data = results.map(r => {
    const agent = agents.find(a => a.id === r.agent_id);
    return {
      agent: r.agent_name,
      emoji: agent?.emoji,
      role: agent?.office_role,
      status: r.status,
      response: r.response,
      tokens: r.tokens_used,
      cost: r.cost_usd,
    };
  });
  const md = data.map(r =>
    `## ${r.agent} (${r.role})\n\nStatus: ${r.status} | Tokens: ${r.tokens} | Cost: $${r.cost.toFixed(4)}\n\n${redactSecrets(r.response)}\n`
  ).join('\n---\n\n');
  triggerDownload(md, `agent-results-${Date.now()}.md`, 'text/markdown');
}

export function exportResultsAsJson(results: AgentResult[], agents: Agent[]): void {
  const data = results.map(r => {
    const agent = agents.find(a => a.id === r.agent_id);
    return {
      agent: r.agent_name,
      emoji: agent?.emoji,
      role: agent?.office_role,
      status: r.status,
      response: r.response,
      tokens: r.tokens_used,
      cost: r.cost_usd,
      time_ms: r.elapsed_ms,
    };
  });
  triggerDownload(JSON.stringify(data, null, 2), `agent-results-${Date.now()}.json`, 'application/json');
}

export function exportLayout(
  officeAgents: OfficeAgent[],
  favorites: Set<string>,
  costBudget: number,
  provider: string,
  customAgents: unknown[],
): void {
  const data = {
    officeAgents,
    favorites: [...favorites],
    costBudget,
    provider,
    customAgents,
  };
  triggerDownload(JSON.stringify(data, null, 2), `agent-office-layout-${Date.now()}.json`, 'application/json');
}

export function exportResultsAsHtml(results: AgentResult[], agents: Agent[]): void {
  const rows = results.map(r => {
    const agent = agents.find(a => a.id === r.agent_id);
    const statusColor = r.status === 'completed' ? '#22c55e' : r.status === 'error' ? '#ef4444' : '#fbbf24';
    return `
      <div style="border:1px solid #333;border-radius:8px;padding:16px;margin-bottom:12px;background:#18181b">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px">
          <span style="font-size:20px">${agent?.name.charAt(0).toUpperCase() || 'A'}</span>
          <strong style="color:#fafafa">${r.agent_name}</strong>
          <span style="color:${statusColor};font-size:12px">${r.status}</span>
          <span style="margin-left:auto;color:#71717a;font-size:12px">${r.tokens_used} tokens · $${r.cost_usd.toFixed(4)}</span>
        </div>
        <pre style="white-space:pre-wrap;color:#a1a1aa;font-size:13px;font-family:Inter,system-ui,sans-serif;margin:0">${escapeHtml(r.response)}</pre>
      </div>`;
  }).join('');

  const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Agent Office Results</title>
<style>body{font-family:Inter,system-ui,sans-serif;background:#0f0f11;color:#fafafa;padding:24px;max-width:800px;margin:0 auto}
h1{font-size:20px;margin-bottom:16px}pre{background:#18181b;padding:12px;border-radius:6px;overflow-x:auto}</style>
</head><body>
<h1>Agent Office Results</h1>
${rows}
<footer style="margin-top:24px;color:#52525b;font-size:12px;border-top:1px solid #333;padding-top:12px">
  Generated by Agent Office · ${new Date().toLocaleString()}
</footer>
</body></html>`;
  triggerDownload(html, `agent-results-${Date.now()}.html`, 'text/html');
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
