// WorkflowTemplates.swift
import Foundation

struct WorkflowTemplates {
    static let all: [WorkflowTemplate] = [
        WorkflowTemplate(id: "full-stack", label: "Full Stack Feature", icon: "square.stack.3d.up",
            prompt: "Build a complete full-stack feature with API endpoint, database schema, frontend component, and tests.",
            agentRoles: ["pm", "be", "dev", "qa"],
            workflowMode: .pipeline, description: "End-to-end feature delivery through pipeline"),
        WorkflowTemplate(id: "code-review", label: "Code Review", icon: "magnifyingglass.circle",
            prompt: "Review the recent changes for code quality, security issues, and performance improvements.",
            agentRoles: ["dev", "qa"],
            workflowMode: .debate, description: "Multi-perspective code review via debate"),
        WorkflowTemplate(id: "api-design", label: "API Design", icon: "network",
            prompt: "Design a RESTful API for this feature including endpoints, request/response schemas, and error handling.",
            agentRoles: ["arch", "be"],
            workflowMode: .synthesis, description: "Architecture + Backend synthesis on API design"),
        WorkflowTemplate(id: "bug-triage", label: "Bug Triage", icon: "ant.fill",
            prompt: "Investigate this bug report, identify root cause, assess impact, and recommend fixes.",
            agentRoles: ["dev", "qa", "support"],
            workflowMode: .parallel, description: "Parallel investigation from multiple angles"),
        WorkflowTemplate(id: "performance-audit", label: "Performance Audit", icon: "gauge.with.dots.needle.67percent",
            prompt: "Audit the system for performance bottlenecks. Profile queries, identify N+1s, and suggest optimizations.",
            agentRoles: ["arch", "be", "data"],
            workflowMode: .parallel, description: "Parallel performance analysis"),
        WorkflowTemplate(id: "security-review", label: "Security Review", icon: "lock.shield",
            prompt: "Perform a security review of the codebase. Check for OWASP Top 10, input validation, and auth issues.",
            agentRoles: ["arch", "qa", "ops"],
            workflowMode: .debate, description: "Debate-driven security assessment"),
        WorkflowTemplate(id: "architecture-rfc", label: "Architecture RFC", icon: "doc.text",
            prompt: "Write an architecture RFC for this proposed change. Include context, alternatives, decision, and consequences.",
            agentRoles: ["arch", "pm", "dev"],
            workflowMode: .synthesis, description: "Synthesize RFC from multiple roles"),
        WorkflowTemplate(id: "test-plan", label: "Test Plan", icon: "checkmark.shield",
            prompt: "Create a comprehensive test plan covering unit, integration, and E2E tests for this feature.",
            agentRoles: ["qa", "dev"],
            workflowMode: .pipeline, description: "QA writes plan, Dev validates feasibility"),
        WorkflowTemplate(id: "migration-plan", label: "Database Migration", icon: "arrow.triangle.2.circlepath",
            prompt: "Plan a safe database migration: schema changes, data migration, rollback strategy, zero-downtime approach.",
            agentRoles: ["arch", "be", "ops"],
            workflowMode: .qualityGate, description: "Migration plan with quality gate before execution"),
        WorkflowTemplate(id: "docs-update", label: "Documentation Update", icon: "book",
            prompt: "Update documentation for this feature: API docs, README sections, inline code comments, and changelog.",
            agentRoles: ["pm", "dev"],
            workflowMode: .collab, description: "Collaborative documentation writing"),
        WorkflowTemplate(id: "deploy-checklist", label: "Deploy Checklist", icon: "checklist",
            prompt: "Create a deployment checklist: pre-deploy checks, deploy steps, post-deploy verification, rollback plan.",
            agentRoles: ["ops", "qa", "pm"],
            workflowMode: .parallel, description: "Parallel checklist creation from each role"),
        WorkflowTemplate(id: "incident-response", label: "Incident Response", icon: "exclamationmark.triangle",
            prompt: "Analyze this incident: timeline, root cause, impact assessment, fix, and prevention measures.",
            agentRoles: ["ops", "arch", "pm"],
            workflowMode: .synthesis, description: "Synthesize incident analysis"),
        WorkflowTemplate(id: "refactor-plan", label: "Refactor Plan", icon: "arrow.triangle.branch",
            prompt: "Plan a refactor: identify technical debt, propose clean architecture changes, estimate effort, and risk.",
            agentRoles: ["arch", "dev"],
            workflowMode: .debate, description: "Debate on refactor approach"),
        WorkflowTemplate(id: "product-spec", label: "Product Spec", icon: "doc.plaintext",
            prompt: "Write a product specification: user stories, acceptance criteria, edge cases, and success metrics.",
            agentRoles: ["pm", "ux", "dev"],
            workflowMode: .pipeline, description: "PM → UX → Dev pipeline"),
        WorkflowTemplate(id: "cost-optimization", label: "Cost Optimization", icon: "dollarsign.circle",
            prompt: "Analyze cloud/resource costs and propose optimizations. Cover compute, storage, network, and third-party APIs.",
            agentRoles: ["ops", "arch", "data"],
            workflowMode: .parallel, description: "Parallel cost analysis"),
    ]
}
